scrape.py, www/index.html, www/instances.json
=> network_performance and family_type for current generation instances

in/index.html.mako, render.py
I pulled the trigger too fast on PR https://github.com/powdahound/ec2instances.info/pull/99 and props to @powdahound for merging it before I could fix it ;-)
=> Remove outdated CPU information completely

scrape.py, www/index.html, www/instances.json
One-line change to account for the extra table on the instance types page and a scrape run to pick up the data. Looks like there were some price reductions as well.
=> Add M4 instance types

in/index.html.mako, www/default.css, www/default.js
Cleaning up filter HTML for better function on smaller devices
Added compare feature for selected rows
=> Filter mobile support and compare feature

.gitignore, README.md, fabfile.py, in/index.html.mako, render.py, scrape.py, www/default.js, www/index.html, www/instances.json
Added option to show instances which require VPC.
I guess I could've added index.html and instances.json to ignore list ;)
=> Vpc ec2classic

fabfile.py
* binding to 127.0.0.1 makes it safer
* use first free port to avoid collisions with other services
* print handy output
* ipv4 only ;)
=> Make fab server to bind to 127.0.0.0 and first free port

in/index.html.mako, in/rds.html.mako, rds.py
Add support for the new Ohio region.
This adds a few `ERROR: Trouble generating reserved price: KeyError('yrTerm3.partialUpfront-quantity',)`.
=> Add support for the newly us-east-2 (Ohio) region.

rds.py
removed reference to heavy and medium 
added m4 family
=> Added m4 Family and  Update reserved_mapping

in/index.html.mako, scrape.py, www/index.html, www/instances.json
=> Include CPU Credit information for T2 instances

scrape.py
=> Add i3 to vpc only

scrape.py
Pulling in more CPU info from https://aws.amazon.com/ec2/instance-types/#instance-type-matrix
Added fields:
* physical_processor
* clock_speed_ghz
* intel_avx
* intel_avx2
* intel_turbo
=> Add CPU details

in/index.html.mako, www/default.js
=> Per second multiplier for EC2 view

Dockerfile, fabfile.py
- Reduced build time and image size;
- Removed unnecessary Dockerfile instructions;
- Combined yum commands;
- Use caching mechanism for `requirements.txt`
- Introduced environment variables for host and port parameters of serve() function with defaults values;
Before:
```bash
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ec2instances.info   latest              9ee46a66b63d        24 seconds ago      559MB
```
After:
```bash
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ec2instances.info   latest              7d11ddb3dbb7        12 seconds ago      344MB
```
Tested with: 
- `Docker for Mac: 17.06.2-ce-mac27 (19124)`
=> Dockerfile optimization

rds.py
8cea5fa
Handling when RDS location is 'Any'
This just falls back to the flagship region (us-east-1)
a1d05cd
Rebuilding
=> Handling when RDS location is 'Any'

scrape.py
=> Added support for new C5 instances

in/index.html.mako, www/default.css, www/default.js
=> Add column for max_enis

in/index.html.mako, scrape.py
This all looks good locally, pricing appears in the right areas and manually checking against the pricing on the AWS pricing page shows they are correct. It does make the list quite long but wasn't sure of a nice way around that.
Fixes #335.
=> Add Linux with SQL Instances

scrape.py
Addresses https://github.com/powdahound/ec2instances.info/issues/341
=> Adding c5d instance types

in/index.html.mako, scrape.py, www/rds/index.html
=> Add EMR support

fabfile.py, in/index.html.mako, scrape.py, www/default.js
Adding data as requested in #361
=> Add EBS as NVMe info

scrape.py
It looks like AWS must've added a `<b>` tag to the header cells so we grab the text content ignoring inner tags.
This commit also adds info on Intel AVX-512 support since that seems to have appeared.
=> Fix CPU info details

in/index.html.mako, in/rds.html.mako
It could be pulled from botocore but I'm not sure how to make it sort the items in the same order we have now and what to do with China regions for which there is no data.
=> Add Stockholm region

tasks.py
=> Gzip the html files before uploading

in/index.html.mako, in/rds.html.mako
Basically copying what #404 does.
=> Add Hong Kong region

ec2.py, scrape.py
Before this fix all `ebs_as_nvme` properties were set to `false` as the scraping broke in `check_ebs_as_nvme`
=> Fix check ebs as nvme

ec2.py, in/index.html.mako, render.py, www/default.js
- Correcting AVX-512 availability
in the application
=> FIX_AVX-512 - Correcting AVX-512

scrape.py
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/accelerated-computing-instances.html#gpu-instance-specifications
https://www.reddit.com/r/MachineLearning/comments/30reky/how_many_cuda_cores_in_a_aws_g2_instance_im/
=> Update g2.2xlarge available GPU memory

scrape.py
https://aws.amazon.com/ec2/instance-types/g4/
=> Add G4 Accelerated Family

www/default.js
I found it quite useful to be able to share a subset of selected instances with others.
=> Persist "Compare Selected" state

scrape.py
The current code doesn't work. I've reverted the URLs to the old ones but please double check everything is working correctly.
=> Fixing the urls, the dynamic ones no longer seem to work

in/index.html.mako, in/rds.html.mako
Fixes #492
Doesn't work without #494 but I'm not sure about #494 being correct.
=> Add af-south-1 (Cape Town)

in/index.html.mako, in/rds.html.mako
https://aws.amazon.com/about-aws/whats-new/2020/04/announcing-the-new-aws-europe-milan-region/
=> Added new eu-south-1 (Milan) region

scrape.py
=> Fixing warning in scrape.py

scrape.py
=> gpu count and cuda cores

README.md
https://quay.io/ssro/ec2instances.info
=> removing outdated Docker image link and easier to copy README commands

README.md
This pull request updates the README to properly reflect the project status. I also mentioned the fact that there is API access to the data backing the site.
=> Updating README to reflect project status

scrape.py
This will resolve #574. Thank you, @mswilson
=> Add p4d.24xlarge GPU details in. 

in/index.html.mako, in/rds.html.mako
prev: https://github.com/vantage-sh/ec2instances.info/pull/495, https://github.com/vantage-sh/ec2instances.info/pull/497
https://aws.amazon.com/blogs/aws/now-open-aws-asia-pacific-jakarta-region/
running into issues with both the new and old Dockerfile trying to test (on M1 and Intel Macs even without my changes)
=> ap-southeast-3 (Jakarta)

www/default.js
This will fix the placeholder text for every Search input field.
=> Bugfix: search input fields

.prettierignore, .prettierrc.js, .travis.yml, Makefile, README.md, default.nix, www/default.css, www/default.js, www/store/store.js
This PR sets up a prettier config and ignore file, and runs it across some of the main files!
=> apply prettier to relevant js/yml/md files

.github/workflows/lint.yml, Makefile, README.md, ec2.py, rds.py, render.py, scrape.py, scripts/package.py, setup.py, tasks.py
This PR sets up black formatting, and runs it across all the relevant python files in the repo!
=> apply black formatter to python files, add github action

.github/workflows/lint.yml, .gitignore, default.nix
This PR adds a similar formatting check to #621 but for prettier. It also adds some helper tools and scripts to test github actions locally!
=> add prettier github action, add a way to test our github actions locally

README.md
Just running prettier to fix some README.md issues after the set of merges!
=> fixup readme formatting

detail_pages_ec2.py, detail_pages_rds.py, ec2.py, render.py, scrape.py, tasks.py
I noticed that the `black` check that runs on Github Actions was not passing successfully on `master`. This PR just applies and commits all the suggested formatting changes, so that it starts passing again.
Nothing too groundbreaking ;-) No change is expected apart from the formatting changes.
You can verify that everything passes by running `black --check .` from the repo's root directory.
=> Apply `black` autoformatting suggestions

www/default.js
#567 
Seems to work for Api Name field
=> Make filters which are valid regexps be treated as regexps

README.md, docs/terraform/iam.tf
=> Update docs/Terraform to inclue Elasticache read permissions

next/components/IndividualColumnFilter.tsx, next/utils/colunnData/azure.tsx, next/utils/colunnData/cache.tsx, next/utils/colunnData/ec2/columns.tsx, next/utils/colunnData/opensearch.tsx, next/utils/colunnData/rds.tsx, next/utils/colunnData/redshift.tsx, next/utils/colunnData/shared.ts
=> Merge staging into production

next/utils/colunnData/azure.tsx, next/utils/colunnData/cache.tsx, next/utils/colunnData/ec2/columns.tsx, next/utils/colunnData/opensearch.tsx, next/utils/colunnData/rds.tsx, next/utils/colunnData/redshift.tsx
=> Fix price sorting showing unavailable at the top

next/components/HalfEC2Root.tsx
My editor didn't save this one the other day, so some of the half roots will have a lower a11y score. This fixes that.
=> Forgot to save this the other day

diff-writer/chain.go, diff-writer/main.go
Oops, the data captured wasn't super good due to this error. This fixes that. Data in the future should be better!
=> Make the lookup key the provider type

next/app/global-error.tsx, next/components/Advert.tsx, next/components/CurrencySelector.tsx, next/components/Filters.tsx, next/components/PricingCalculator.tsx, next/state.ts, next/utils/abGroup.ts, next/utils/migrations.ts, next/utils/useGlobalStateValue.ts
I've only seen this once so far, and doing this will still make the state a imperfect experience for users with local storage off, but this tries to make it as good as possible and stops any crashing (even gets crash with a SecurityError for some reason).
=> Handle if the user disallows us from using local storage

next/instrumentation-client.ts
Reducing rate of Sentry collection as we are hitting billing limits.
=> chore: Reduce sentry collection of replays and tracing.
