vantage-sh/ec2instances.info

render.py
The cc1 instance type has been removed from the AWS site and no longer shows up on the ec2instances.info site. This PR simply removes dead code.
=> Remove references to cc1 instance types

render.py
This PR removes outdated cpu info that is no longer explicitly specified by Amazon. Additionally it fixes https://github.com/powdahound/ec2instances.info/issues/97.
Please note that this is based off of https://github.com/powdahound/ec2instances.info/pull/98. I can rebase on master if https://github.com/powdahound/ec2instances.info/pull/98 is rejected.
=> Remove outdated CPU information

scrape.py, www/index.html, www/instances.json
since we have both current and previous generation instances in the json, need to identify the generation of a particular instance. thus, add generation name (current or previous) to instance types
=> add generation name (current or previous) to instance types

www/default.js
Splitting up the cpu column into ECU + Cores shifted linux cost along by one and the default sort index wasn't changed accordingly. This uses the right index.
=> Use correct sort index for linux cost

in/index.html.mako, scrape.py, www/default.js, www/index.html, www/instances.json
I was interested in the specific MB/s for each instance and saw it's included for the EBS optimized instances, so this PR adds those.
=> Add max bandwidth for EBS optimized instances

render.py, scrape.py, www/index.html, www/instances.json
Updates to include the new `t2.large` instance type.
The [Instance Type Matrix for Amazon Linux AMIs](http://aws.amazon.com/amazon-linux-ami/instance-type-matrix/) has changed:
* No longer includes a 5th column specifying `HVM (Graphics)` type instances.
* No longer includes data for some previous generation instance classes: `m1`, `c1`, `cc2`, `cg1`, `m2`, `cr1`, `hi1`,  `hs1`, `t1`.
This means that the `g2` type instances now show `HVM` for their `Linux Virtualization` column, and the above listed types now show `Unknown`, which we already show for `cg1.4xlarge` (I assume for the same reasons).
Since there is already a precedent for `cg1.4xlarge` showing `Unknown`, and these are all legacy instance types I think we are OK to not worry about adding manual support to retain their …
=> Support for t2.large instances

in/index.html.mako, www/default.js, www/index.html
"Search" allows regex compare. New filter allows multiple values
filtering such as specifying the minimum memory needed, and min ECU.
This does not impact sorting, so you can pick your min requirements and find the cheapest instance type.
=> Add row filtering by min value.

scrape.py
The indexes for the family tables were off-by-one, likely due to a recent update to the page.
=> scrape: fix instance family queries

www/default.js
Base monthly cost on 365/12 days instead of 30.
=> Use average month cost instead of 30d base

scrape.py
Dug up some information around the instance types where Linux Virtualization currently shows "Unknown". Unfortunately I wasn't able to find anything specific on cr1. Sources below.
https://aws.amazon.com/blogs/aws/next-generation-cluster-computing-on-amazon-ec2-the-cc2-instance-type/
> This instance type uses hardware-assisted virtualization (HVM), so you’ll need to choose an AMI accordingly.
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using_cluster_computing.html
> You can launch CG1 and G2 instances using any HVM AMI.
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/storage_instances.html
> Using **Linux paravirtual (PV) AMIs**, HI1 instances can deliver more than 120,000 4 KB random read IOPS and between 10,000 and 85,000 4 KB random write IOPS (depending on active logical …
=> More manual virtualisation data

render.py, scrape.py
This PR makes three updates:
- Add _Up to 10 Gigabit_  and _20 Gigabit_ to the ranked list so Network Performance sorts properly
- Update the VPC only instance types based on the latest information from http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-vpc.html#vpc-only-instance-types.
- Add pretty names for the p2/r4/x1 types.
=> Update 'Network Performance' Rankings and Fix 'VPC Only' for p2/r4/x1

in/base.mako, www/default.js
This integrates DataTables buttons into the project in order to enable export
as CSV functionality.
See here: https://datatables.net/extensions/buttons/examples/initialisation/export.html
(There are a couple other features, but in the interest of space, kept just the CSV)
Change to UI
=> Feature Request: CSV Export #166

scrape.py
This pull request corrects several AWS typos and a moved table for the new I3 instance types in issue #227
=> Correct multiple AWS typos with the new I3 instance typos

in/index.html.mako, scrape.py, www/default.js
Notable changes
- Parse storage info from http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html
instead of the instance information page.
- Add a table column about need of warming up storage volumes
- Add a table column about SSD TRIM support
- Add information about additional swap volumes
- Add information about NVMe for the SSD volumes
- Use integers as storage measurement unit
Known regressions due to issues in the data source, already reported to AWS:
- incorrect information for i3.8xlarge and i3.16xlarge - update: fixed already
- missing data for F1 instance types, incorrectly displayed as EBS-only
=> Large refactoring of storage scraping, fixes #220

in/index.html.mako, scrape.py
This also updates the pricing information after the most recent [price reduction](https://aws.amazon.com/blogs/aws/category/price-reduction/) and exposes the 3year term no upfront reserved prices, thus fixing #249.
=> Fix fab build error, partially fixes #250

www/default.js
1. Alongside the display value, the sort attribute of span is also changed now
2. After region change, the datatable is notified of data change through the use of datatable.rows().invalidate().draw()
=> Temporary fix for the sorting bug when region changed

scrape.py
seems that there was an unneeded space in the class name for the instance type matrix table.
=> issue in add_linux_ami_info

scrape.py
I need the GPU field to be consistently typed in order to support the implementation of https://github.com/cristim/autospotting/issues/126
My Go library providing instance type information based on the ec2instances.info data (https://github.com/cristim/ec2-instances-info) would otherwise fail to parse the JSON data structure since the type defaults to int for the zero value but it's currently a string for all non-zero values.
=> Convert GPU count to an int to ensure type consistency

scrape.py
AWS now has separate EC2 Instance pricing for Red Hat Enterprise Linux, SUSE Linux Enterprise Server and Windows with SQL Enterprise. These have been added to the EC2 pricing scrape to populate the instances.json file
=> Add rhel, sles and mswinSQLEnterprise platforms to EC2 pricing scrape

.gitignore, MANIFEST.in, Makefile, scripts/package.py, setup.py
This adds a build process that turns the final json output into Python source data that client libraries can include. It publishes a very slim artifact to PyPi as 'ec2instances.info'
There are various gists and snippets of code on StackOverflow for screen-scraping ec2instances.info. This allows at least Python developers to avoid having to do that.
Published as ec2instances.info-0.0.1 on PyPi and I've added @powdahound as an owner
=> Packaging instance data as a pypi library

render.py
That column is showing `Yes` or empty. Should be something like,
`2.3 (base) 2.7 (turbo)` or `2.4`
=> Fix clock_speend column display

in/index.html.mako, in/rds.html.mako
The data is already being populated as far as I can tell. We just need a drop-down entry to fix it.
You have to manually edit the URL currently.
See: https://www.ec2instances.info/?region=us-gov-west-1&cost_duration=monthly&selected=m4.2xlarge
Fixes: https://github.com/powdahound/ec2instances.info/issues/194
=> Add drop-down item for AWS GovCloud

rds.py
* add the region 'Asia Pacific (Osaka-Local)' aka ap-northeast-3
* be more robust in the scrapping if 'productFamily' is not there.
With the new region we get the following products without
'productFamily field':
``` python
{u'attributes': {u'fromLocation': u'Asia Pacific (Osaka-Local)',
u'fromLocationType': u'AWS Region',
u'operation': u'',
u'servicecode': u'AWSDataTransfer',
u'servicename': u'AWS Data Transfer',
u'toLocation': u'External',
u'toLocationType': u'Other',
u'transferType': u'Inter Region Peering Data Transfer Outbound',
u'usagetype': u'APN3-AWS-Out-Bytes'},
u'sku': u'8FHV4XVBMZ49CCC4'}
{u'attributes': {u'fromLocation': u'External',
u'fromLocationType': u'AWS Region',
u'operation': u'',
u'servicecode': u'AWSDataTransfer',
u'servicename': u'AWS Data Transfer',
u'toLocation': …
```
=> two fixes on the rds scrapper

requirements.txt
The update to the Fabric package causes the tool to fail complaining about `fabric.api` not existing any longer, pinning to the 1.x versions fixes this.
I'm not confident enough to try updating it to the 2.x release so hopefully this is acceptable as it should get the builds passing again :)
=> Pin Fabric to a version prior to 2.0.0 release (fixes builds)

scrape.py
This PR simply adds the missing m5d instances, just like https://github.com/powdahound/ec2instances.info/pull/342 did for c5d. 👍
=> Add missing m5d instance type

scrape.py
It looks like AWS haven't included all cells in one of the rows of the table here so we just skip past it with some defensive code.
=> Fix Linux virtualization types

scrape.py
Several of new instances should be VPC only but are marked incorrectly, instead of adding them to the list flip the condition so only ec2 classic instances are marked as No.
Data taken from: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-classic-platform.html#ec2-classic-instance-types
=> Fix "VPC Only" column

.gitignore, .travis.yml, Dockerfile, README.md, requirements.txt, tasks.py
https://www.fabfile.org/upgrading.html#sidegrading-to-invoke
This reduces the number of dependencies needed for the project and also removes
the first stumbling block for running the project with Python 3.
Invoke makes use of a `Context` object which contains the context where the
tasks are run inside of. It is supplied to the tasks as the first positional
argument so I had to add a `c` argument to all the tasks to make this work.
Invoke doesn't have an `abort` function like Fabric has, so I have instead
simplified it to just print the abort message and then exit with a status code
of 1.
=> Switch from Fabric to Invoke

.gitignore, .travis.yml, Dockerfile, README.md, in/index.html.mako, in/rds.html.mako, rds.py, render.py, requirements.txt, scrape.py, tasks.py
**NOTE:** This PR is based on top of the branch which #381 was created from, so it also contains the same commits as they are a necessary predecessor for adding Python 3 support.
-----
This adds support for Python 3 to the code base alongside Python 2 support. The [six](https://six.readthedocs.io/) library was used in a few places to be able to support both, but shouldn't be intrusive at all.
I have tries to make each commit concerned with only one aspect of this, so I'd suggest going through them one by one to get a better idea of what has changed.
=> Python 3 support

in/index.html.mako
Add the Osaka (ap-northeast-3) region. Currently there's only data for the reserved pricing being scraped but #389 will add the on-demand pricing for Osaka as well.
=> Add the Osaka region

README.md
I noticed the README doesn't actually link to the production site, so I added that link.
=> add link to site from README

in/index.html.mako, in/rds.html.mako, rds.py
https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/
still looking into adding the China regions as well, because those didn't show any prices this way
Would be nice to get all of the region mapping in one central place too
=> adding new AWS regions (Paris, Osaka, GovCloud East)

rds.py
The `us-gov-west-1` region is stated as  `AWS GovCloud (US)` in the data source, not US-West, now it should be the same as EC2s.
M5 instances now have 3 year-no upfront reserved option.
=> Fix the Gov West region in RDS and add 3 year no upfront reserved

ec2.py
Fix the regression in #401 
It should match the output for `curl -sL https://github.com/powdahound/ec2instances.info/raw/9692781cf5fc9410fbb0d9532afcb97fb6f52483/www/instances.json | jq '.[] | {type: .instance_type, family: .family}'` but it may differ a bit.
=> Fix instance families (#401)

www/default.js
I love ec2instances.info, I use it frequently. EC2 instance shopping is intrinsically an optimization problem. You always know your instance requirements and you're trying to find the best fit for the lowest cost. It is a constraint-based problem as well. You have "soft" and "hard" constraints, meaning things you can and cannot compromise in your search, respectively.
Say I have a hard constraint on storage, "EBS only" and network performance of "High" but a soft constraint on RAM and CPU. The ec2instances site in its current state is difficult because I have only one search textbox for my hard constraints, I can search by one or the other. The end result is I search by one of these constraints, sort on the other, and spend significant time sorting and scrolling to compare the instances I …
=> Add support for column filters

www/default.js
My apologies. It appears my column sorting introduced a minor bug. This PR is a fix for the bug.
To build column sorting a second "table-header" row is added to the table at initialization time.
It turns out that DataTables, by default, places column sorting controls on the lowest "table-header" row.
I personally believe in our case column sorting should remain the same as it always has, on the top row.
See this screenshot as an example:
I ironically discovered this bug this morning when using your site to shop for a new EC2 instance.
Fortunately, thanks to the power of DataTables, the fix is very basic. Change the default behavior and enforce the top-header-row controls the sorting by [setting "orderCellsTop" to true](https://datatables.net/reference/option/orderCellsTop).
The end result …
=> Ensure first row in the table has sorting control

render.py
https://github.com/powdahound/ec2instances.info/issues/350
Quick fix. We could make this more future-proof by parsing the numbers out of text. Would be even easier if we can drop the `Up to ` that's in some of the cells
=> adding more network performance sorting options

in/base.mako, in/index.html.mako, in/rds.html.mako, render.py, www/default.js
Even with a very decent internet connection, the page takes a few good seconds to load. A big part of it seems to be all the serialized JSON data in a lot of the columns. You can actually see Chrome drawing it row by row as it's loading.
I've changed it up a little so that all the pricing data is in one big object at the end of the file. This way the browser can load the initial table, display it, and then load the rest of the data.
I've also "compressed" the pricing dictionary by using integers for the keys instead of long strings like `"yrTerm1Convertible.partialUpfront`" that repeat for each instance type and each region.
Those two together reduced `index.html` from 16mb to 5.7mb (uncompressed). It also feels like it loads faster because you don't see the row by row rendering.
I hope …
=> Improve page load speed

ec2.py, in/index.html.mako, in/rds.html.mako
We have a new region available so it added it to the menus.
Additionally it seems that Bahrain contains a few new instance types (c5d.metal, cd5.12xl, c5d.24xl) that are not in us-east-1 so are not parsed correctly. I've added a try/catch to prevent the task from failing, hopefully they will be added to N. Virginia soon. Otherwise 
Also the Travis CI is currently showing the build as passing while it actually should be failed.
=> Add Bahrain region + fix build errors cause by Bahrain

render.py
The '75 Gigabit' option was missing and the index defaulted to zero. This should fix that
At this time, sorting by network speed shows 75 Gigabits before 100 - which is wrong.
=> Fix network speed sorting

rds.py
Addresses #479 
I have no way of confirming if 210 and 220 are the only required `engineCode` to ignore but they seem to reflect Outpost running of MySQL and PostgreSQL
Have built and confirmed this resolves the issues reported there - diff of old and new instances.json makes sense.
(there are plenty of errors reported as in other PRs due to unknown sku)
=> Issue 479 - Filter out Outposts

ec2.py, render.py
This fixes #487 
Also remove an unneeded region alias workaround.
=> Add "Up to 5 Gigabit" to the network performance sort order

ec2.py, scrape.py
AWS currently has support for both the x86 and ARM architectures, so the old assumption that everything was x86_64 unless there was a 32-bit pricing option doesn't apply.  Fortunately, AWS provides the list of supported architectures as part of the DescribeInstanceTypes call, so we can will support any new architectures that they come out with.
=> Use the instance type data to populate the architecture list

ec2.py, in/base.mako, in/index.html.mako, render.py, scrape.py, www/default.js
This update provides the list of supported availability zones for every instance type. This was originally proposed in #439.
Screenshots:
=> Availability Zones

scrape.py
g2.8xlarge uses 4 instance of K250 gpu, each with 4GB memory.
=> correction for g2.8xlarge total gpu mem

ec2.py, in/index.html.mako, www/default.js
This implements #109.
Current status:
- adds Spot price to the EC2 pricing scraper
- data seems to be added correctly to `instances.json`, we now have a list of Spot prices within a region, as well as the min/max values saved as additional fields, which are also shown in the UI. The list can potentially be used for some automation use cases, but may need to be enriched a bit, maybe with some physical AZ information.
- data is exposed to the UI as shown in the screenshot below
- data is now shown for all instance types and seems correct
M5DN.xlarge in Frankfurt, compared to the AWS console pricing history view to see that data matches
Same M5DN.xlarge in Frankfurt, but with monthly view:
You can see this live at  https://spot-on-ec2-instances-info.netlify.app/
This work was contributed by …
=> Add EC2 Spot pricing information

in/index.html.mako, in/rds.html.mako, render.py, www/default.css, www/default.js, www/rds/index.html
This PR adds a couple of UI tweaks that were useful to me recently:
- added menu to render costs by more than just instance, i.e. vCPU, ECU, etc.
- added column and filter to more conveniently visualize the mem/vCPU profiles
if this goes through, i also have a branch with an additional button to hide/show the units suffixes to reduce the visual noise.
=> a couple of minor UI add-ons: pricing by more than just instance, filter by mem/vCPU profile 

scrape.py
This resolves #593 - I've manually added G5 GPU details based on the public G5 launch blog post, product page and asking a few AWS folks on Twitter.
=> G5 GPU details added

Dockerfile, README.md
- Update/simplify the `Dockerfile`, for building in Amazon Linux 2 instead of Centos 7, because AL2 has many of the required packages preinstalled.
- Update `README.md` to make Docker the recommended way of running it locally and a few minor content updates.
- Fix a number of linting issues reported by `markdownlint` on `README.md`.
Fixes #580.
=> Fix/docker build, README updates.

scrape.py
There were some changes on the page detailing burst credits, including the addition of a new table, which broke the scraper, causing base_performance and burst_minutes to be null for all burstable instances. This updates the xpath so those fields are set again.
=> Fix scraper for burst credits

www/default.js
also addresses closed issues #274, #353, #385, #426, #529, and #543
We can also upgrade https://cdn.datatables.net/buttons/ which is now on version 2.2.3 and we are using version 1.2.4 (see `base.mako`)
There are still state management issues. For availability zones, you must have it as a showing column first. Then when you change the region the AZ will change. If you have the AZ column hidden, change the reason, then show it, the AZ will be us-east-1
=> should fix #615 and #554

ec2.py
Addresses the following exception when running `python3 ./scrape.py`:
```
Traceback (most recent call last):
File "./scrape.py", line 1054, in <module>
scrape("www/instances.json")
File "./scrape.py", line 1018, in scrape
add_pricing_info(all_instances)
File "./scrape.py", line 234, in add_pricing_info
ec2.add_pricing(by_type)
File "/home/dghai/ec2instances.info/ec2.py", line 198, in add_pricing
add_spot_pricing(imap)
File "/home/dghai/ec2instances.info/ec2.py", line 269, in add_spot_pricing
price["ProductDescription"], "NA"
File "/home/dghai/ec2instances.info/ec2.py", line 38, in translate_platform_name
return os[operating_system] + software[preinstalled_software]
KeyError: 'Red Hat Enterprise Linux (Amazon VPC)'
```
=> Add new OS available from EC2 + make translate_platform_name a little more robust

ec2.py
This helps remove this workaround https://github.com/LeanerCloud/ec2-instances-info/blob/master/Makefile#L21 and also makes the data file slightly smaller.
```
root@bfcdece0c60e:/opt/app# curl -s localhost:8080/instances.json  | grep eu-west | wc -l
2585
root@bfcdece0c60e:/opt/app# curl -s localhost:8080/instances.json  | grep cn | wc -l
0
```
=> Avoid creation of empty data for Chinese regions

README.md
- Updated reference for the API docs. 
- Fixed some funky spacing.
- Fixed Slack link to new redirect link.
=> Update API docs section

in/index.html.mako
The current link is redirected anyway, so let's save a redirect!
=> Change link from AWS t2 instances page to the generic burstable page.

Dockerfile, README.md, docker-compose.yaml, in/rds.html.mako
Previously we only had Standard, added also Express, Web and Enterprise.
This also includes some docker-compose improvements I had locally, submitted those previously but nobody seemed to care ;-)
=> Expose all Microsoft SQL Server license prices

detail_pages_cache.py, in/cache.html.mako, in/instance-type-cache.html.mako
Turns out we already had the data in the JSON file, just needed to show it in the UI
Fixes #760
=> Add Valkey engine pricing data for Elasticache

opensearch.py
This was caused by missing instance type key for Serverless and other SKU types
```
1586.4 Traceback (most recent call last):
1586.4   File “/opt/app/tasks.py”, line 100, in scrape_opensearch
1586.4     opensearch_scrape(opensearch_file)
1586.4   File “/opt/app/opensearch.py”, line 126, in scrape
1586.4     instance_type = attributes[“instanceType”]
1586.4 KeyError: ‘instanceType’
1586.4 ERROR: Unable to scrape OpenSearch data
1586.4 None
```
=> Fix crash in OpenSearch scraper
